# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev17+g93c5ed4.d20230427'
__version_tuple__ = version_tuple = (0, 1, 'dev17', 'g93c5ed4.d20230427')
